name: parot_ai
description: "Parot - Your friendly speech-learning companion."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.1
  supabase_flutter: ^2.8.3
  google_sign_in: ^6.2.1
  flutter_tts: ^4.2.5
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  provider: ^6.1.1
  intl: ^0.20.2
  flutter_chat_ui: ^2.11.1
  flutter_chat_types: ^3.6.2
  lottie: ^3.3.2
  cached_network_image: ^3.4.1

  flutter_animate: ^4.5.0
  chat_bubbles: ^1.6.0
  avatar_glow: ^3.0.1
  fl_chart: ^0.68.0
  uuid: ^4.5.2
  flutter_chat_core: ^2.9.0
  shared_preferences: ^2.3.3
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  emoji_picker_flutter: ^3.1.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.1
  flutter_svg: ^2.0.9
  image_picker: ^1.2.1
  liquid_swipe: ^3.1.0
  url_launcher: ^6.3.2
  hugeicons: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: 0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/bgline.jpg
    - assets/coaching_illustration.png
    - assets/chatbg.jpg
    - assets/coaching_illustration_3d.png
    - assets/google_logo.png
    - assets/illus1.png
    - assets/undraw_social-ideas_3znc.svg
    - assets/handdraws/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
